name: On This Day Pipeline

on:
  workflow_dispatch:
    inputs:
      month:
        description: 'Mes en formato MM (ejemplo: 08)'
        required: true
        default: '01'
      day:
        description: 'Día en formato DD (ejemplo: 20)'
        required: true
        default: '01'

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Llamar API On This Day
        run: |
          echo "Ejecutando consulta al API..."
          RESPONSE=$(curl -s "https://byabbe.se/on-this-day/${{ github.event.inputs.month }}/${{ github.event.inputs.day }}/events.json?lang=${{ vars.LANGUAGE }}")
          echo "Respuesta del API:"
          echo "$RESPONSE" | jq .
