name: Wikipedia Pipeline

on:
  workflow_dispatch:
    inputs:
      month:
        description: 'Mes (formato MM)'
        required: true
        default: '01'
      day:
        description: 'Día (formato DD)'
        required: true
        default: '01'

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar API OnThisDay
        id: call_api
        run: |
          echo "Consultando API de Wikimedia..."
          curl --location --request GET "https://api.wikimedia.org/feed/v1/wikipedia/es/onthisday/all/${{ github.event.inputs.month }}/${{ github.event.inputs.day }}" > response.json
      
      - name: create hash
        id: json_hash
        run: |
          echo "hash=$(echo -n '${{ response.json }}' | sha256sum | cut -d ' ' -f1)" >> $GITHUB_OUTPUT

      - name: Cache json
        id: cache-json
        uses: actions/cache@v4
        env:
          cache-name: cache-json
        with:
          path: response.json
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ steps.json_hash.outputs.hash }}

      
      