name: Wikipedia Pipeline

on:
  workflow_dispatch:
    inputs:
      month:
        description: 'Mes (formato MM)'
        required: true
        default: '01'
      day:
        description: 'Día (formato DD)'
        required: true
        default: '01'

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Llamar API On This Day
        run: |
          echo "Ejecutando consulta al API..."
          RESPONSE=$(curl --location --request GET "https://api.wikimedia.org/feed/v1/wikipedia/lang=${{ vars.LANG }}/onthisday/all/${{ github.event.inputs.month }}/${{ github.event.inputs.day }}")
          echo "Respuesta del API:"
          echo "$RESPONSE" | jq .
