name: Wikipedia Pipeline

on:
  workflow_dispatch:
    inputs:
      month:
        description: 'Mes (formato MM)'
        required: true
        default: '01'
      day:
        description: 'Día (formato DD)'
        required: true
        default: '01'

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar API OnThisDay
        run: |
          echo "Consultando API de Wikimedia..."
          curl --location --request GET "https://api.wikimedia.org/feed/v1/wikipedia/es/onthisday/all/${{ github.event.inputs.month }}/${{ github.event.inputs.day }}" -s | jq .
