name: Wikipedia Pipeline

on:
  workflow_dispatch:
    inputs:
      month:
        description: 'Mes (formato MM)'
        required: true
        default: '01'
      day:
        description: 'Día (formato DD)'
        required: true
        default: '01'

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:

      - name: Restaurar cache
        id: cache
        uses: actions/cache@v3
        with:
          path: response.json
          key: ${{ env.CACHE_KEY }}

      - name: Llamar API OnThisDay
        id: call_api
        run: |
          echo "Consultando API de Wikimedia..."
          curl --location --request GET "https://api.wikimedia.org/feed/v1/wikipedia/es/onthisday/all/${{ github.event.inputs.month }}/${{ github.event.inputs.day }}" > response.json
      
      - name: Guardar cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: response.json
          key: ${{ env.CACHE_KEY }}

      - name: Parsear eventos
        id: parse
        run: |
          urls=$(jq -r '.selected[].pages[0].content_urls.desktop.page' response.json)
          echo "events<<EOF" >> $GITHUB_OUTPUT
          echo "$urls" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      
      