name: Wikipedia Pipeline

on:
  workflow_dispatch:
    inputs:
      month:
        description: 'Mes (formato MM)'
        required: true
        default: '01'
      day:
        description: 'Día (formato DD)'
        required: true
        default: '01'

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Cache JSON file
        id: cache-json
        uses: actions/cache@v4
        with:
          path: response.json
          key: ${{ runner.os }}-json-${{ hashFiles('response.json') }}
          restore-keys: |
            ${{ runner.os }}-json-
            
      - name: Llamar API OnThisDay
        if: steps.cache-json.outputs.cache-hit != 'true'
        id: call_api
        run: |
          echo "Consultando API de Wikimedia..."
          curl --location --request GET "https://api.wikimedia.org/feed/v1/wikipedia/es/onthisday/all/${{ github.event.inputs.month }}/${{ github.event.inputs.day }}" > response.json
          echo "respuesta del API" > $response.json

      - name: Check Cache Status
        run: |
          if [ "${{ steps.cache-json.outputs.cache-hit }}" == "true" ]; then
            echo "Se utilizó caché en esta ejecución."
          else
            echo "No se utilizó caché en esta ejecución."
          fi


      
      